from .AILab_MegaTTS import NODE_CLASS_MAPPINGS as MEGATTS_NODE_CLASS_MAPPINGS
from .AILab_MegaTTS import NODE_DISPLAY_NAME_MAPPINGS as MEGATTS_NODE_DISPLAY_NAME_MAPPINGS
from .MegaTTS_VoiceMaker import NODE_CLASS_MAPPINGS as VOICEMAKER_NODE_CLASS_MAPPINGS
from .MegaTTS_VoiceMaker import NODE_DISPLAY_NAME_MAPPINGS as VOICEMAKER_NODE_DISPLAY_NAME_MAPPINGS

from .MegaTTS_utils import get_voice_samples, get_voice_path

NODE_CLASS_MAPPINGS = {
    **MEGATTS_NODE_CLASS_MAPPINGS,
    **VOICEMAKER_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MEGATTS_NODE_DISPLAY_NAME_MAPPINGS,
    **VOICEMAKER_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']